### ISSUE TITLE
Upgrade to PMD 7.0.0

### ISSUE THREAD

**Issue by adangel** [ChuckJonas/vscode-apex-pmd#159]
**Is your feature request related to a problem? Please describe.**
Since PMD 7.0.0 is now released, it would make sense to ship the latest version.

As far as I see from the commit messages, currently PMD 7.0.0-rc3 is included.

**Describe the solution you'd like**
Either use 7.0.0 or wait till 7.1.0.

**Additional context**
- requires fix for #158

**Comment by rsoesemann** [comment]
Since the update the extension doesnt do anything anymore. No errors no icon changes.

I always used it with my own local PMD. Stopped working now. But also without a local PMD.

@adangel any idea what I am doing wrong?
<img width="1313" alt="Screenshot_2024-04-29_at_15_23_01" src="https://github.com/ChuckJonas/vscode-apex-pmd/assets/8180281/9cbeb400-5f21-4e19-8e49-b49a53569937">
