### ISSUE TITLE
PMD Path not set. Please see installation instructions.

### ISSUE THREAD

**Issue by arudhran** [ChuckJonas/vscode-apex-pmd#17]
Hello
I am using VS Code and run into this error.  

> PMD Path not set. Please see installation instructions.

I double checked my settings.Json and I do have an entry  
`"apexPMD.pmdPath": "/Users/Arudhran/PMD" `
which is where I have extracted the Zip file. I tried it on a Mac and got the exact same error. Please let me know if I am doing something wrong.

**Comment by nchursin** [comment]
Hi!

That's strange, I just reinstalled PMD on my Mac and it works perfectly fine...

Could you please share what exactly is in your `/Users/Arudhran/PMD` directory?

**Comment by ChuckJonas** [comment]
@nchursin long term, it might be worth considering the pros & cons of actually just including the JAR in the vscode package by default (assuming the licensing allows it).  That would allow people to run this package without additional install instructions.  

We would probably want to still have the custom setting to the jar path to allow users to override it (otherwise we'd need to keep the jar up-to-date more often).

**Comment by arudhran** [comment]
Hi Nikita
Sorry for the delayed response as I was out on vacation. The PMD directory
contains the lib and bin folders. I tried re-installing/Disabling the
extension and unfortunately encountering the same error.




*Regards,Arudhran Thirumurugan*

**Comment by ChuckJonas** [comment]
@arudhran what do you see if you open a terminal and run `ls /Users/Arudhran/PMD`?  

Also, we are about to release an update that will have the PMD binaries packaged in the extension which should allow it to run without any configuration.

**Comment by ChuckJonas** [comment]
these types of installation errors should no longer be an issue with the newest release
