### ISSUE TITLE
default setting missing: apexPMD.useDefaultRuleset : true

### ISSUE THREAD

**Issue by SalesforceBobLightning** [ChuckJonas/vscode-apex-pmd#26]
**Describe the bug**

The "apexPMD.useDefaultRuleset" settings is missing from the defaults, so Visual Studio Code complains when I add it to the User settings

**Versions (please complete the following information):**
 - OS: Windows 10

Version: 1.28.0 (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by ChuckJonas** [comment]
@SalesforceBobLightning previously we had two settings to manage the ruleset `useDefaultRuleset` & `rulesetPath`.  This was sort of redundant, so we got rid of `useDefaultRuleset` and changed the behavior so that as long as `rulesetPath` is NOT set it will use the default.


However, it looks like we still have some references to it, so I'll make sure those get removed.  Thanks!
