### ISSUE TITLE
Ability to export the results after Run on workspace command

### ISSUE THREAD

**Issue by samrat2385** [ChuckJonas/vscode-apex-pmd#59]
**Is your feature request related to a problem? Please describe.**

**Additional context**
![image](https://user-images.githubusercontent.com/50947124/60441877-d1371000-9c0f-11e9-9754-3d59733325f2.png)
there are so many issues across multiple files i would be handy to be able to export all in any format as csv, xml, excel

**Comment by ChuckJonas** [comment]
The errors actually start in CSV form (csv string is returned by [this func](https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/src/lib/apexPmd.ts#L145)), so this wouldn't be too difficult.

Would welcome a PR for this but I probably won't invest any time into it, since this is pretty much the functionality offered by the naked PMD jar.

If you enable `showStdOut` you'll see the actually PMD command we are running (output on [this line](https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/src/lib/apexPmd.ts#L165)).

You can simply grab this command and execute it in a terminal and it should give you what you are looking for (simply pipe the output to a new file or copy it from the terminal std out).
